#spring.application.name=ConfigServer
server.port=8888

spring.application.name=config-server

spring.cloud.config.server.git.uri=https://github.com/Mental-bicep/MicroServiceProject
# Git branch name
spring.cloud.config.server.git.default-label=main
# Sub-folder where files live inside repo
spring.cloud.config.server.git.search-paths=config
# Clones repo immediately upon server startup
spring.cloud.config.server.git.clone-on-start=true