server:
  port: 8085

spring:
  application:
    name: api-gateway          # Lowercase (Spring Boot convention)
  cloud:
    gateway:
      routes:
        - id: booking-service-route
          uri: lb://BOOKING-SERVICE    # Uppercase (Eureka registry lookup key)
          predicates:
            - Path=/irctc/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 5
                key-resolver: "#{@ipKeyResolver}"

        - id: payment-service-route
          uri: lb://PAYMENT-SERVICE    # Uppercase (Eureka registry lookup key)
          predicates:
            - Path=/pay/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0 # Sample 100% of requests (Use 0.1 / 10% in high-scale production)
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans # Zipkin server URL

# Custom log pattern to output [app-name, traceId, spanId]
logging:
  pattern:
    level: "%5p [%${spring.application.name:},%X{traceId:-},%X{spanId:-}]"