spring.application.name=NotificationService
server.port=8083

# Eureka Setup
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Kafka Consumer Setup
spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest